### ISSUE TITLE
Project link in repo header and README

### ISSUE THREAD

**Issue by mecm1993** [React-Dominicana/dominicans-who-code-react#13]
The production [URL](https://festive-pike-7fadeb.netlify.com/) should be available inside the repo.

**Comment by GianCastle** [comment]
Nice catch. In the morning I deployed the repo to Netlify; at that moment, the repository wasnt on the organization. I need to remap the repo on Netifly so that it can point to the organization repository.

In order to do that, I need more permissions on the organization or maybe @amaurygomez  or @HarysVizcaino  can address this issue as well.

Cheers!
